[features]
seeds = false
[programs.devnet]
gifportal = "82wpSArZHYT41sZHTBzLv7FMr1anD5JCMLFfeKZ5zKU2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tahliltahlil/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
