[features]
seeds = false
[programs.devnet]
gifportal = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/tahliltahlil/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
